"""Exhaust binary actions on three local physical states.

The script computes the exact relational fibers generated by arbitrary legal
insert/delete histories up to a capacity.  It is a finite structural explorer:
an action with useful fibers is only a candidate until its public-tape FPR is
checked for fixed histories.
"""

from __future__ import annotations

import argparse
import itertools
import math

from search_cyclic_cayley_quotients import (
    bisect_root,
    calibrated_load,
    ogf,
    ogf_mean,
)


Permutation = tuple[int, int, int]


def compose(left: Permutation, right: Permutation) -> Permutation:
    return tuple(right[left[i]] for i in range(3))


def inverse(permutation: Permutation) -> Permutation:
    result = [0, 0, 0]
    for source, target in enumerate(permutation):
        result[target] = source
    return tuple(result)  # type: ignore[return-value]


def fibers(
    insert_actions: tuple[Permutation, Permutation],
    delete_actions: tuple[Permutation, Permutation],
    capacity: int,
) -> list[list[set[int]]]:
    """fibers[c][state] is the set of feasible one-counts."""
    reachable = {(0, 0, 0)}
    changed = True
    while changed:
        changed = False
        for load, ones, state in tuple(reachable):
            for symbol in (0, 1):
                if load < capacity:
                    successor = (
                        load + 1,
                        ones + symbol,
                        insert_actions[symbol][state],
                    )
                    if successor not in reachable:
                        reachable.add(successor)
                        changed = True
                if (symbol == 0 and load > ones) or (symbol == 1 and ones > 0):
                    successor = (
                        load - 1,
                        ones - symbol,
                        delete_actions[symbol][state],
                    )
                    if successor not in reachable:
                        reachable.add(successor)
                        changed = True

    result = [[set() for _ in range(3)] for _ in range(capacity + 1)]
    for load, ones, state in reachable:
        result[load][state].add(ones)
    return result


def rejection_capability(layer: list[set[int]], load: int) -> tuple[int, int]:
    """Number of states certifying all-zero and all-one compositions."""
    zero_only = sum(bool(values) and values == {0} for values in layer)
    one_only = sum(bool(values) and values == {load} for values in layer)
    return zero_only, one_only


def insertion_rejection_profile(
    insert_actions: tuple[Permutation, Permutation],
    structure: list[list[set[int]]],
    capacity: int,
) -> list[float]:
    distribution = [1.0, 0.0, 0.0]
    result = [1.0]
    for load in range(1, capacity + 1):
        successor = [0.0, 0.0, 0.0]
        for state, mass in enumerate(distribution):
            for symbol in (0, 1):
                successor[insert_actions[symbol][state]] += mass / 2.0
        distribution = successor
        rejection = 0.0
        for state, mass in enumerate(distribution):
            values = structure[load][state]
            if values == {0} or values == {load}:
                rejection += mass / 2.0
        result.append(rejection)
    return result


def formal_rate(counts: list[int], rejection: list[float]) -> float:
    """Rate after freezing the final searched layer as a zero-rejection tail."""
    load = calibrated_load(rejection)
    saddle = bisect_root(
        lambda z: ogf_mean(z, counts) - load,
        1e-12,
        1.0 - 1e-12,
    )
    return (
        math.log(ogf(saddle, counts)) / load - math.log(saddle)
    ) / math.log(2.0)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--capacity", type=int, default=8)
    parser.add_argument("--all-maps", action="store_true")
    parser.add_argument("--top", type=int, default=30)
    args = parser.parse_args()
    permutations = list(itertools.permutations(range(3)))
    actions = list(itertools.product(range(3), repeat=3)) if args.all_maps else permutations
    found = 0
    best_by_profile: dict[
        tuple[float, ...],
        tuple[
            float,
            list[float],
            tuple[Permutation, Permutation],
            tuple[Permutation, Permutation],
            list[list[set[int]]],
        ],
    ] = {}
    insert_choices = actions if args.all_maps else permutations
    for zero_action in insert_choices:
        for one_action in insert_choices:
            for delete_zero in actions:
                for delete_one in actions:
                    if args.all_maps:
                        insert_actions = (zero_action, one_action)
                    else:
                        if delete_zero != inverse(zero_action) or delete_one != inverse(one_action):
                            continue
                        insert_actions = (zero_action, one_action)
                    structure = fibers(
                        insert_actions,
                        (delete_zero, delete_one),
                        args.capacity,
                    )
                    rejection = insertion_rejection_profile(
                        insert_actions,
                        structure,
                        args.capacity,
                    )
                    counts = [
                        sum(bool(values) for values in layer)
                        for layer in structure
                    ]
                    # The final layer is treated as the constant tail.  Only
                    # accept candidates whose rejection has already vanished
                    # there, so this extension is semantically conservative.
                    if rejection[-1] != 0.0:
                        continue
                    if any(value > 0.0 for value in rejection[1:]):
                        found += 1
                        rate = formal_rate(counts, rejection)
                        key = tuple(round(value, 12) for value in rejection)
                        candidate = (
                            rate,
                            rejection,
                            insert_actions,
                            (delete_zero, delete_one),
                            structure,
                        )
                        incumbent = best_by_profile.get(key)
                        if incumbent is None or rate < incumbent[0]:
                            best_by_profile[key] = candidate
    best = sorted(best_by_profile.values(), key=lambda item: item[0])
    shown = 0
    for rate, rejection, insert_actions, delete_actions, structure in best:
        print(
            f"Rformal={rate:.12f} rho={rejection} i={insert_actions} "
            f"d={delete_actions} fibers={structure}"
        )
        shown += 1
        if shown == args.top:
            break
    print(f"positive={found} profiles={len(best_by_profile)} shown={shown}")


if __name__ == "__main__":
    main()
