#!/usr/bin/env python3
"""Search four-symbol weighted-tree pair-move lattices.

For a tree T with positive integer edge weights w_e, the load-preserving
lattice is generated by w_e(e_i-e_j).  A syndrome is represented by the
subtree loads modulo w_e after rooting T.  Exact profiles use integer walk
counts and support unions; rate comparisons are numerical candidate search.
"""

from __future__ import annotations

import argparse
import itertools
import math
from collections import defaultdict


def rooted_subtrees(edges, root=0):
    adjacency = [[] for _ in range(4)]
    for edge_index, (left, right) in enumerate(edges):
        adjacency[left].append((right, edge_index))
        adjacency[right].append((left, edge_index))

    parent = [-1] * 4
    parent_edge = [-1] * 4
    order = [root]
    for vertex in order:
        for neighbor, edge_index in adjacency[vertex]:
            if neighbor == parent[vertex]:
                continue
            parent[neighbor] = vertex
            parent_edge[neighbor] = edge_index
            order.append(neighbor)

    subtree = [set([vertex]) for vertex in range(4)]
    for vertex in reversed(order[1:]):
        subtree[parent[vertex]] |= subtree[vertex]
    result = [None] * 3
    for vertex in order[1:]:
        result[parent_edge[vertex]] = subtree[vertex]
    return tuple(frozenset(value) for value in result)


def increments(edges, weights):
    subtrees = rooted_subtrees(edges)
    return tuple(
        tuple((1 if symbol in subtrees[edge] else 0) % weights[edge] for edge in range(3))
        for symbol in range(4)
    )


def add(left, right, weights):
    return tuple((left[i] + right[i]) % weights[i] for i in range(3))


def exact_profile(edges, weights):
    incs = increments(edges, weights)
    zero = (0, 0, 0)
    walk = {zero: 1}
    unions = {zero: 0}
    order = math.prod(weights)
    states = []
    rejection = []
    for load in range(2 * order + 1):
        states.append(len(walk))
        rejected = sum(
            multiplicity * (4 - unions[state].bit_count())
            for state, multiplicity in walk.items()
        )
        rejection.append(rejected / 4 ** (load + 1))
        if len(walk) == order and all(mask == 15 for mask in unions.values()):
            return tuple(states), tuple(rejection), load, order

        next_walk = defaultdict(int)
        next_unions = defaultdict(int)
        for state, multiplicity in walk.items():
            for symbol, increment in enumerate(incs):
                target = add(state, increment, weights)
                next_walk[target] += multiplicity
                next_unions[target] |= unions[state] | (1 << symbol)
        walk = dict(next_walk)
        unions = dict(next_unions)
    raise AssertionError("profile failed to stabilize")


def evaluate(edges, weights):
    states, rejection, cutoff, order = exact_profile(edges, weights)

    def poisson(lam):
        term = math.exp(-lam)
        result = term * rejection[0]
        for load in range(1, len(rejection)):
            term *= lam / load
            result += term * rejection[load]
        return result

    left, right = 0.0, 10.0
    for _ in range(100):
        middle = (left + right) / 2
        if poisson(middle) > 0.5:
            left = middle
        else:
            right = middle
    lam = (left + right) / 2

    def ogf(z):
        return sum(states[c] * z**c for c in range(cutoff)) + order * z**cutoff / (1 - z)

    def mean(z):
        numerator = sum(c * states[c] * z**c for c in range(cutoff))
        numerator += order * (
            cutoff * z**cutoff / (1 - z) + z ** (cutoff + 1) / (1 - z) ** 2
        )
        return numerator / ogf(z)

    left, right = 1e-14, 1 - 1e-14
    for _ in range(100):
        middle = (left + right) / 2
        if mean(middle) < lam:
            left = middle
        else:
            right = middle
    z = (left + right) / 2
    rate = math.log2(ogf(z)) / lam - math.log2(z)
    return rate, lam, z, states, rejection, cutoff


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--max-weight", type=int, default=12)
    parser.add_argument("--top", type=int, default=40)
    args = parser.parse_args()
    topologies = {
        "path": ((0, 1), (1, 2), (2, 3)),
        "star": ((0, 1), (0, 2), (0, 3)),
    }
    candidates = []
    for topology, edges in topologies.items():
        for weights in itertools.product(range(1, args.max_weight + 1), repeat=3):
            if topology == "path" and weights[0] > weights[2]:
                continue
            if topology == "star" and tuple(sorted(weights)) != weights:
                continue
            result = evaluate(edges, weights)
            candidates.append((result[0], topology, weights, result))
    for rate, topology, weights, result in sorted(candidates)[: args.top]:
        print(
            f"R={rate:.12f} {topology} w={weights} lambda={result[1]:.9f} "
            f"z={result[2]:.9f} cutoff={result[5]} d={result[3]} rho={result[4]}"
        )


if __name__ == "__main__":
    main()
